module "redshift_sdp_cluster_val" {
  # aws_iam_role_amazon_eventbridge_invoke_glue_869551675_assume_role_policy   = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"events.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_amazon_eventbridge_invoke_glue_869551675_managed_policy_arns  = ["arn:aws:iam::511434321460:policy/service-role/Amazon_EventBridge_Invoke_Glue_869551675"]
  # aws_iam_role_amazon_eventbridge_invoke_glue_869551675_max_session_duration = 3600
  # aws_iam_role_amazon_eventbridge_invoke_glue_869551675_name                 = "Amazon_EventBridge_Invoke_Glue_869551675"
  # aws_iam_role_amazon_eventbridge_invoke_glue_869551675_path                 = "/service-role/"
  # aws_iam_role_amazon_eventbridge_invoke_glue_869551675_tc_category          = "iam"
  # aws_iam_role_amazonec2rolefordatapipelinerole_assume_role_policy           = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_amazonec2rolefordatapipelinerole_description                  = "Provides access to S3, DynamoDB, and other services for EC2 instances that Data Pipeline launches."
  # aws_iam_role_amazonec2rolefordatapipelinerole_managed_policy_arns          = ["arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforDataPipelineRole"]
  # aws_iam_role_amazonec2rolefordatapipelinerole_max_session_duration         = 3600
  # aws_iam_role_amazonec2rolefordatapipelinerole_name                         = "AmazonEC2RoleforDataPipelineRole"
  # aws_iam_role_amazonec2rolefordatapipelinerole_path                         = "/"
  # aws_iam_role_amazonec2rolefordatapipelinerole_tc_category                  = "iam"
  # aws_iam_role_awsgluedatabrewservicerole_test_assume_role_policy            = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"databrew.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsgluedatabrewservicerole_test_managed_policy_arns           = ["arn:aws:iam::511434321460:policy/service-role/AwsGlueDataBrewServicePolicyForInputS3-test", "arn:aws:iam::511434321460:policy/service-role/AwsGlueDataBrewServicePolicyForOutputS3-test", "arn:aws:iam::aws:policy/service-role/AWSGlueDataBrewServiceRole"]
  # aws_iam_role_awsgluedatabrewservicerole_test_max_session_duration          = 3600
  # aws_iam_role_awsgluedatabrewservicerole_test_name                          = "AWSGlueDataBrewServiceRole-test"
  # aws_iam_role_awsgluedatabrewservicerole_test_path                          = "/service-role/"
  # aws_iam_role_awsgluedatabrewservicerole_test_tc_category                   = "iam"
  # aws_iam_role_awsglueservicesagemakernotebookrole_test_assume_role_policy   = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"sagemaker.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsglueservicesagemakernotebookrole_test_managed_policy_arns  = ["arn:aws:iam::511434321460:policy/service-role/AWSGlueServiceSageMakerNotebookRole-test"]
  # aws_iam_role_awsglueservicesagemakernotebookrole_test_max_session_duration = 3600
  # aws_iam_role_awsglueservicesagemakernotebookrole_test_name                 = "AWSGlueServiceSageMakerNotebookRole-test"
  # aws_iam_role_awsglueservicesagemakernotebookrole_test_path                 = "/service-role/"
  # aws_iam_role_awsglueservicesagemakernotebookrole_test_tc_category          = "iam"
  # aws_iam_role_awsserviceroleforcomputeoptimizer_assume_role_policy          = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"compute-optimizer.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforcomputeoptimizer_managed_policy_arns         = ["arn:aws:iam::aws:policy/aws-service-role/ComputeOptimizerServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforcomputeoptimizer_max_session_duration        = 3600
  # aws_iam_role_awsserviceroleforcomputeoptimizer_name                        = "AWSServiceRoleForComputeOptimizer"
  # aws_iam_role_awsserviceroleforcomputeoptimizer_path                        = "/aws-service-role/compute-optimizer.amazonaws.com/"
  # aws_iam_role_awsserviceroleforcomputeoptimizer_tc_category                 = "iam"
  # aws_iam_role_awsserviceroleforelasticloadbalancing_assume_role_policy      = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"elasticloadbalancing.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforelasticloadbalancing_description             = "Allows ELB to call AWS services on your behalf."
  # aws_iam_role_awsserviceroleforelasticloadbalancing_managed_policy_arns     = ["arn:aws:iam::aws:policy/aws-service-role/AWSElasticLoadBalancingServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforelasticloadbalancing_max_session_duration    = 3600
  # aws_iam_role_awsserviceroleforelasticloadbalancing_name                    = "AWSServiceRoleForElasticLoadBalancing"
  # aws_iam_role_awsserviceroleforelasticloadbalancing_path                    = "/aws-service-role/elasticloadbalancing.amazonaws.com/"
  # aws_iam_role_awsserviceroleforelasticloadbalancing_tc_category             = "iam"
  # aws_iam_role_awsserviceroleforemrcleanup_assume_role_policy                = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"elasticmapreduce.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforemrcleanup_managed_policy_arns               = ["arn:aws:iam::aws:policy/aws-service-role/AmazonEMRCleanupPolicy"]
  # aws_iam_role_awsserviceroleforemrcleanup_max_session_duration              = 3600
  # aws_iam_role_awsserviceroleforemrcleanup_name                              = "AWSServiceRoleForEMRCleanup"
  # aws_iam_role_awsserviceroleforemrcleanup_path                              = "/aws-service-role/elasticmapreduce.amazonaws.com/"
  # aws_iam_role_awsserviceroleforemrcleanup_tc_category                       = "iam"
  # aws_iam_role_awsservicerolefororganizations_assume_role_policy             = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"organizations.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsservicerolefororganizations_description                    = "Service-linked role used by AWS Organizations to enable integration of other AWS services with Organizations."
  # aws_iam_role_awsservicerolefororganizations_managed_policy_arns            = ["arn:aws:iam::aws:policy/aws-service-role/AWSOrganizationsServiceTrustPolicy"]
  # aws_iam_role_awsservicerolefororganizations_max_session_duration           = 3600
  # aws_iam_role_awsservicerolefororganizations_name                           = "AWSServiceRoleForOrganizations"
  # aws_iam_role_awsservicerolefororganizations_path                           = "/aws-service-role/organizations.amazonaws.com/"
  # aws_iam_role_awsservicerolefororganizations_tc_category                    = "iam"
  # aws_iam_role_awsserviceroleforredshift_assume_role_policy                  = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"redshift.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforredshift_description                         = "Allows Amazon Redshift to call AWS services on your behalf "
  # aws_iam_role_awsserviceroleforredshift_managed_policy_arns                 = ["arn:aws:iam::aws:policy/aws-service-role/AmazonRedshiftServiceLinkedRolePolicy"]
  # aws_iam_role_awsserviceroleforredshift_max_session_duration                = 3600
  # aws_iam_role_awsserviceroleforredshift_name                                = "AWSServiceRoleForRedshift"
  # aws_iam_role_awsserviceroleforredshift_path                                = "/aws-service-role/redshift.amazonaws.com/"
  # aws_iam_role_awsserviceroleforredshift_tc_category                         = "iam"
  # aws_iam_role_awsserviceroleforschemas_assume_role_policy                   = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"schemas.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforschemas_description                          = "Enables access to the Managed Rules created by AWS Schemas."
  # aws_iam_role_awsserviceroleforschemas_managed_policy_arns                  = ["arn:aws:iam::aws:policy/aws-service-role/AmazonEventBridgeSchemasServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforschemas_max_session_duration                 = 3600
  # aws_iam_role_awsserviceroleforschemas_name                                 = "AWSServiceRoleForSchemas"
  # aws_iam_role_awsserviceroleforschemas_path                                 = "/aws-service-role/schemas.amazonaws.com/"
  # aws_iam_role_awsserviceroleforschemas_tc_category                          = "iam"
  # aws_iam_role_awsserviceroleforsso_assume_role_policy                       = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"sso.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforsso_description                              = "Service-linked role used by AWS SSO to manage AWS resources, including IAM roles, policies and SAML IdP on your behalf."
  # aws_iam_role_awsserviceroleforsso_managed_policy_arns                      = ["arn:aws:iam::aws:policy/aws-service-role/AWSSSOServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforsso_max_session_duration                     = 3600
  # aws_iam_role_awsserviceroleforsso_name                                     = "AWSServiceRoleForSSO"
  # aws_iam_role_awsserviceroleforsso_path                                     = "/aws-service-role/sso.amazonaws.com/"
  # aws_iam_role_awsserviceroleforsso_tc_category                              = "iam"
  # aws_iam_role_awsserviceroleforsupport_assume_role_policy                   = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"support.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsserviceroleforsupport_description                          = "Enables resource access for AWS to provide billing, administrative and support services"
  # aws_iam_role_awsserviceroleforsupport_managed_policy_arns                  = ["arn:aws:iam::aws:policy/aws-service-role/AWSSupportServiceRolePolicy"]
  # aws_iam_role_awsserviceroleforsupport_max_session_duration                 = 3600
  # aws_iam_role_awsserviceroleforsupport_name                                 = "AWSServiceRoleForSupport"
  # aws_iam_role_awsserviceroleforsupport_path                                 = "/aws-service-role/support.amazonaws.com/"
  # aws_iam_role_awsserviceroleforsupport_tc_category                          = "iam"
  # aws_iam_role_awsservicerolefortrustedadvisor_assume_role_policy            = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"trustedadvisor.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_awsservicerolefortrustedadvisor_description                   = "Access for the AWS Trusted Advisor Service to help reduce cost, increase performance, and improve security of your AWS environment."
  # aws_iam_role_awsservicerolefortrustedadvisor_managed_policy_arns           = ["arn:aws:iam::aws:policy/aws-service-role/AWSTrustedAdvisorServiceRolePolicy"]
  # aws_iam_role_awsservicerolefortrustedadvisor_max_session_duration          = 3600
  # aws_iam_role_awsservicerolefortrustedadvisor_name                          = "AWSServiceRoleForTrustedAdvisor"
  # aws_iam_role_awsservicerolefortrustedadvisor_path                          = "/aws-service-role/trustedadvisor.amazonaws.com/"
  # aws_iam_role_awsservicerolefortrustedadvisor_tc_category                   = "iam"
  # aws_iam_role_datapipelinedefaultresourcerole_assume_role_policy            = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_datapipelinedefaultresourcerole_description                   = "Provides access to S3, DynamoDB, and other services for EC2 instances that Data Pipeline launches."
  # aws_iam_role_datapipelinedefaultresourcerole_managed_policy_arns           = ["arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforDataPipelineRole"]
  # aws_iam_role_datapipelinedefaultresourcerole_max_session_duration          = 3600
  # aws_iam_role_datapipelinedefaultresourcerole_name                          = "DataPipelineDefaultResourceRole"
  # aws_iam_role_datapipelinedefaultresourcerole_path                          = "/"
  # aws_iam_role_datapipelinedefaultresourcerole_tc_category                   = "iam"
  # aws_iam_role_datapipelinedefaultrole_assume_role_policy                    = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"datapipeline.amazonaws.com\",\"elasticmapreduce.amazonaws.com\"]},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_datapipelinedefaultrole_description                           = "Allows Data Pipeline and Data Pipeline managed EMR clusters to call AWS services on your behalf."
  # aws_iam_role_datapipelinedefaultrole_managed_policy_arns                   = ["arn:aws:iam::aws:policy/service-role/AWSDataPipelineRole"]
  # aws_iam_role_datapipelinedefaultrole_max_session_duration                  = 3600
  # aws_iam_role_datapipelinedefaultrole_name                                  = "DataPipelineDefaultRole"
  # aws_iam_role_datapipelinedefaultrole_path                                  = "/"
  # aws_iam_role_datapipelinedefaultrole_tc_category                           = "iam"
  # aws_iam_role_emr_autoscaling_defaultrole_assume_role_policy                = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"elasticmapreduce.amazonaws.com\",\"application-autoscaling.amazonaws.com\"]},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_emr_autoscaling_defaultrole_managed_policy_arns               = ["arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforAutoScalingRole"]
  # aws_iam_role_emr_autoscaling_defaultrole_max_session_duration              = 3600
  # aws_iam_role_emr_autoscaling_defaultrole_name                              = "EMR_AutoScaling_DefaultRole"
  # aws_iam_role_emr_autoscaling_defaultrole_path                              = "/"
  # aws_iam_role_emr_autoscaling_defaultrole_tc_category                       = "iam"
  # aws_iam_role_emr_defaultrole_assume_role_policy                            = "{\"Version\":\"2008-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"elasticmapreduce.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_emr_defaultrole_managed_policy_arns                           = ["arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceRole"]
  # aws_iam_role_emr_defaultrole_max_session_duration                          = 3600
  # aws_iam_role_emr_defaultrole_name                                          = "EMR_DefaultRole"
  # aws_iam_role_emr_defaultrole_path                                          = "/"
  # aws_iam_role_emr_defaultrole_tc_category                                   = "iam"
  # aws_iam_role_emr_ec2_defaultrole_assume_role_policy                        = "{\"Version\":\"2008-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_emr_ec2_defaultrole_managed_policy_arns                       = ["arn:aws:iam::aws:policy/service-role/AmazonElasticMapReduceforEC2Role"]
  # aws_iam_role_emr_ec2_defaultrole_max_session_duration                      = 3600
  # aws_iam_role_emr_ec2_defaultrole_name                                      = "EMR_EC2_DefaultRole"
  # aws_iam_role_emr_ec2_defaultrole_path                                      = "/"
  # aws_iam_role_emr_ec2_defaultrole_tc_category                               = "iam"
  # aws_iam_role_etl_trigger_lambda_role_3fjwqh2w_assume_role_policy           = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_etl_trigger_lambda_role_3fjwqh2w_managed_policy_arns          = ["arn:aws:iam::511434321460:policy/service-role/AWSLambdaVPCAccessExecutionRole-45cf7e49-c6ef-4d08-aaa0-0b7b24ff1828", "arn:aws:iam::511434321460:policy/service-role/AWSLambdaBasicExecutionRole-039e75c9-d6c7-4a98-b5fa-f530aa92ae23"]
  # aws_iam_role_etl_trigger_lambda_role_3fjwqh2w_max_session_duration         = 3600
  # aws_iam_role_etl_trigger_lambda_role_3fjwqh2w_name                         = "etl-trigger-lambda-role-3fjwqh2w"
  # aws_iam_role_etl_trigger_lambda_role_3fjwqh2w_path                         = "/service-role/"
  # aws_iam_role_etl_trigger_lambda_role_3fjwqh2w_tc_category                  = "iam"
  # aws_iam_role_etl_trigger_lambda_role_chbz6yjx_assume_role_policy           = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"lambda.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_etl_trigger_lambda_role_chbz6yjx_managed_policy_arns          = ["arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole", "arn:aws:iam::511434321460:policy/service-role/AWSLambdaBasicExecutionRole-3a0db95a-32c8-4398-a85f-57994ee63014", "arn:aws:iam::511434321460:policy/service-role/AWSLambdaVPCAccessExecutionRole-665ebc38-3d66-4b0e-b93e-e025b1a9be05"]
  # aws_iam_role_etl_trigger_lambda_role_chbz6yjx_max_session_duration         = 3600
  # aws_iam_role_etl_trigger_lambda_role_chbz6yjx_name                         = "etl-trigger-lambda-role-chbz6yjx"
  # aws_iam_role_etl_trigger_lambda_role_chbz6yjx_path                         = "/service-role/"
  # aws_iam_role_etl_trigger_lambda_role_chbz6yjx_tc_category                  = "iam"
  # aws_iam_role_firehoserole_0b8cf500_assume_role_policy                      = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"firehose.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_firehoserole_0b8cf500_description                             = "Role to allow firehose stream put events into S3 backup bucket"
  # aws_iam_role_firehoserole_0b8cf500_inline_policy_name                      = "Firehose-S3Access"
  # aws_iam_role_firehoserole_0b8cf500_inline_policy_policy                    = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":[\"s3:AbortMultipartUpload\",\"s3:GetBucketLocation\",\"s3:GetObject\",\"s3:ListBucket\",\"s3:ListBucketMultipartUploads\",\"s3:PutObject\"],\"Resource\":[\"arn:aws:s3:::newrelic-delivery-stream-firehose-backup-0b8cf500\",\"arn:aws:s3:::newrelic-delivery-stream-firehose-backup-0b8cf500/*\"],\"Effect\":\"Allow\"}]}"
  # aws_iam_role_firehoserole_0b8cf500_max_session_duration                    = 3600
  # aws_iam_role_firehoserole_0b8cf500_name                                    = "FirehoseRole-0b8cf500"
  # aws_iam_role_firehoserole_0b8cf500_path                                    = "/service-role/"
  # aws_iam_role_firehoserole_0b8cf500_tc_category                             = "iam"
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_assume_role_policy       = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"glue.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_description              = "Allows Glue to call AWS services on your behalf. "
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_managed_policy_arns      = ["arn:aws:iam::aws:policy/AdministratorAccess", "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole", "arn:aws:iam::aws:policy/AWSGlueConsoleFullAccess", "arn:aws:iam::aws:policy/AmazonRedshiftDataFullAccess", "arn:aws:iam::511434321460:policy/sdp-s3-policy", "arn:aws:iam::aws:policy/AmazonRedshiftFullAccess"]
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_max_session_duration     = 3600
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_name                     = "lunar2-dp-non-prod-glue-service-role"
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_path                     = "/"
  # aws_iam_role_lunar2_dp_non_prod_glue_service_role_tc_category              = "iam"
  # aws_iam_role_metricsstreamrole_0b8cf500_assume_role_policy                 = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"streams.metrics.cloudwatch.amazonaws.com\"},\"Action\":\"sts:AssumeRole\",\"Condition\":{\"StringEquals\":{\"sts:ExternalId\":\"511434321460\"}}}]}"
  # aws_iam_role_metricsstreamrole_0b8cf500_description                        = "Role to allow a metric stream put metrics into a firehose"
  # aws_iam_role_metricsstreamrole_0b8cf500_inline_policy_name                 = "MetricStreams-FirehosePutRecords"
  # aws_iam_role_metricsstreamrole_0b8cf500_inline_policy_policy               = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":[\"firehose:PutRecord\",\"firehose:PutRecordBatch\"],\"Resource\":\"arn:aws:firehose:us-west-2:511434321460:deliverystream/NewRelic-Delivery-Stream\",\"Effect\":\"Allow\"}]}"
  # aws_iam_role_metricsstreamrole_0b8cf500_max_session_duration               = 3600
  # aws_iam_role_metricsstreamrole_0b8cf500_name                               = "MetricsStreamRole-0b8cf500"
  # aws_iam_role_metricsstreamrole_0b8cf500_path                               = "/service-role/"
  # aws_iam_role_metricsstreamrole_0b8cf500_tc_category                        = "iam"
  # aws_iam_role_newrelicinfrastructure_integrations_assume_role_policy        = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::754728514883:root\"},\"Action\":\"sts:AssumeRole\",\"Condition\":{\"StringEquals\":{\"sts:ExternalId\":\"3252272\"}}}]}"
  # aws_iam_role_newrelicinfrastructure_integrations_managed_policy_arns       = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
  # aws_iam_role_newrelicinfrastructure_integrations_max_session_duration      = 3600
  # aws_iam_role_newrelicinfrastructure_integrations_name                      = "NewRelicInfrastructure-Integrations"
  # aws_iam_role_newrelicinfrastructure_integrations_path                      = "/"
  # aws_iam_role_newrelicinfrastructure_integrations_tc_category               = "iam"
  # aws_iam_role_okta_account_admin_assume_role_policy                         = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Federated\":\"arn:aws:iam::511434321460:saml-provider/Okta\"},\"Action\":\"sts:AssumeRoleWithSAML\",\"Condition\":{\"StringEquals\":{\"SAML:aud\":\"https://signin.aws.amazon.com/saml\"}}}]}"
  # aws_iam_role_okta_account_admin_description                                = "okta-account-admin"
  # aws_iam_role_okta_account_admin_managed_policy_arns                        = ["arn:aws:iam::aws:policy/AdministratorAccess"]
  # aws_iam_role_okta_account_admin_max_session_duration                       = 3600
  # aws_iam_role_okta_account_admin_name                                       = "okta-account-admin"
  # aws_iam_role_okta_account_admin_path                                       = "/"
  # aws_iam_role_okta_account_admin_tc_category                                = "iam"
  # aws_iam_role_okta_idp_cross_account_role_assume_role_policy                = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::421757482782:root\"},\"Action\":\"sts:AssumeRole\",\"Condition\":{}}]}"
  # aws_iam_role_okta_idp_cross_account_role_description                       = "Okta-Idp-cross-account-role"
  # aws_iam_role_okta_idp_cross_account_role_managed_policy_arns               = ["arn:aws:iam::aws:policy/IAMReadOnlyAccess"]
  # aws_iam_role_okta_idp_cross_account_role_max_session_duration              = 3600
  # aws_iam_role_okta_idp_cross_account_role_name                              = "Okta-Idp-cross-account-role"
  # aws_iam_role_okta_idp_cross_account_role_path                              = "/"
  # aws_iam_role_okta_idp_cross_account_role_tc_category                       = "iam"
  # aws_iam_role_organizationaccountaccessrole_assume_role_policy              = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::421757482782:root\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_organizationaccountaccessrole_inline_policy_name              = "AdministratorAccess"
  # aws_iam_role_organizationaccountaccessrole_inline_policy_policy            = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Action\":\"*\",\"Resource\":\"*\"}]}"
  # aws_iam_role_organizationaccountaccessrole_max_session_duration            = 3600
  # aws_iam_role_organizationaccountaccessrole_name                            = "OrganizationAccountAccessRole"
  # aws_iam_role_organizationaccountaccessrole_path                            = "/"
  # aws_iam_role_organizationaccountaccessrole_tc_category                     = "iam"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_all_environment           = "nonprod"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_all_owner                 = "Upendranath Uppala"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_all_purpose               = "Prisma"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_all_terraform             = "true"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_environment               = "nonprod"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_owner                     = "Upendranath Uppala"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_purpose                   = "Prisma"
  # aws_iam_role_prisma_cloud_readonly_role__tc_tags_terraform                 = "true"
  # aws_iam_role_prisma_cloud_readonly_role_assume_role_policy                 = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"arn:aws:iam::188619942792:root\"},\"Action\":\"sts:AssumeRole\",\"Condition\":{\"StringEquals\":{\"sts:ExternalId\":\"e851abbb-c15b-4709-9294-4da4e5e4e375\"}}}]}"
  # aws_iam_role_prisma_cloud_readonly_role_managed_policy_arns                = ["arn:aws:iam::aws:policy/SecurityAudit", "arn:aws:iam::511434321460:policy/prisma-cloud-readonly-nonprod"]
  # aws_iam_role_prisma_cloud_readonly_role_max_session_duration               = 3600
  # aws_iam_role_prisma_cloud_readonly_role_name                               = "prisma-cloud-readonly-role"
  # aws_iam_role_prisma_cloud_readonly_role_path                               = "/"
  # aws_iam_role_prisma_cloud_readonly_role_tc_category                        = "iam"
  # aws_iam_role_sdp_service_role_val_assume_role_policy                       = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"redshift-serverless.amazonaws.com\",\"redshift.amazonaws.com\",\"sagemaker.amazonaws.com\",\"glue.amazonaws.com\"]},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_sdp_service_role_val_managed_policy_arns                      = ["arn:aws:iam::aws:policy/AmazonAppFlowFullAccess", "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole", "arn:aws:iam::511434321460:policy/sdp-secrets-manager-policy", "arn:aws:iam::aws:policy/AmazonRedshiftDataFullAccess", "arn:aws:iam::511434321460:policy/sdp-s3-policy", "arn:aws:iam::aws:policy/AmazonRedshiftAllCommandsFullAccess", "arn:aws:iam::aws:policy/AWSGlueSchemaRegistryFullAccess"]
  # aws_iam_role_sdp_service_role_val_max_session_duration                     = 3600
  # aws_iam_role_sdp_service_role_val_name                                     = "sdp-service-role-val"
  # aws_iam_role_sdp_service_role_val_path                                     = "/"
  # aws_iam_role_sdp_service_role_val_tc_category                              = "iam"
  # aws_iam_role_tableau_dev_assume_role_policy                                = "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"cloudformation.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
  # aws_iam_role_tableau_dev_description                                       = "Allows CloudFormation to create and manage AWS stacks and resources on your behalf."
  # aws_iam_role_tableau_dev_managed_policy_arns                               = ["arn:aws:iam::aws:policy/AdministratorAccess", "arn:aws:iam::aws:policy/AmazonEC2FullAccess", "arn:aws:iam::aws:policy/AmazonS3FullAccess", "arn:aws:iam::aws:policy/IAMFullAccess"]
  # aws_iam_role_tableau_dev_max_session_duration                              = 3600
  # aws_iam_role_tableau_dev_name                                              = "tableau-dev"
  # aws_iam_role_tableau_dev_path                                              = "/"
  # aws_iam_role_tableau_dev_tc_category                                       = "iam"
  # aws_redshift_cluster_sdp_cluster_val_allow_version_upgrade                 = true
  # aws_redshift_cluster_sdp_cluster_val_automated_snapshot_retention_period   = 1
  # aws_redshift_cluster_sdp_cluster_val_availability_zone                     = "us-west-2a"
  # aws_redshift_cluster_sdp_cluster_val_cluster_identifier                    = "sdp-cluster-val"
  # aws_redshift_cluster_sdp_cluster_val_cluster_parameter_group_name          = "default.redshift-1.0"
  # aws_redshift_cluster_sdp_cluster_val_cluster_public_key                    = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCBh5QsrUgkTRowEvEbKOUSi8yN16SfGln5SIVoQsMPtaV2p3AvZ1l+kWXIGMTxvxaBp7XiV1eXUuLn2OL/CAAavZD+BZWrJP3coceRaDhTSr67Dw4FjLg0Wb7FWQgvIxLUOFw5T4cRuldTY4ICNTxOQtRUOJnDPF+DPgF1vupKqZi8/btv/DTF5N77dLnL+uLwcZsUcsJ+dtp1oe/HZUnDbe7XrM3CHOVSedJEjd16Fb1Paz3u7VGsdeBfVR3LJWhLh7mQq5ayVjbnp3yJD8JKdOeJUo+pFgJGXbbNKa7RNuhkg9plBfMuREyCXZc4PAnanPd8zMRj5qmXvVRiHuMB Amazon-Redshift"
  # aws_redshift_cluster_sdp_cluster_val_cluster_revision_number               = "37509"
  # aws_redshift_cluster_sdp_cluster_val_cluster_subnet_group_name             = "sdp-cluster-subnet-group"
  # aws_redshift_cluster_sdp_cluster_val_cluster_type                          = "single-node"
  # aws_redshift_cluster_sdp_cluster_val_cluster_version                       = "1.0"
  # aws_redshift_cluster_sdp_cluster_val_database_name                         = "screeningdb"
  # aws_redshift_cluster_sdp_cluster_val_encrypted                             = true
  # aws_redshift_cluster_sdp_cluster_val_endpoint                              = "sdp-cluster-val.c0p7eva3f80t.us-west-2.redshift.amazonaws.com:5439"
  # aws_redshift_cluster_sdp_cluster_val_enhanced_vpc_routing                  = true
  # aws_redshift_cluster_sdp_cluster_val_iam_roles                             = ["arn:aws:iam::511434321460:role/sdp-service-role-val"]
  # aws_redshift_cluster_sdp_cluster_val_kms_key_id                            = "arn:aws:kms:us-west-2:511434321460:key/d3dbc936-c30f-4295-b563-2403a1c770bb"
  # aws_redshift_cluster_sdp_cluster_val_logging_enable                        = false
  # aws_redshift_cluster_sdp_cluster_val_master_username                       = "sdpuser"
  # aws_redshift_cluster_sdp_cluster_val_node_type                             = "dc2.large"
  # aws_redshift_cluster_sdp_cluster_val_number_of_nodes                       = 1
  # aws_redshift_cluster_sdp_cluster_val_port                                  = 5439
  # aws_redshift_cluster_sdp_cluster_val_preferred_maintenance_window          = "sat:12:30-sat:13:00"
  # aws_redshift_cluster_sdp_cluster_val_skip_final_snapshot                   = true
  # aws_redshift_cluster_sdp_cluster_val_tc_category                           = "redshift"
  # aws_redshift_cluster_sdp_cluster_val_vpc_security_group_ids                = ["sg-0d67b2c2a40ac96ef"]
  source = "./modules/redshift"

aws_redshift_cluster_allow_version_upgrade                 = var.aws_redshift_cluster_sdp_cluster_val_allow_version_upgrade
aws_redshift_cluster_automated_snapshot_retention_period   = var.aws_redshift_cluster_sdp_cluster_val_automated_snapshot_retention_period
aws_redshift_cluster_availability_zone                     = var.aws_redshift_cluster_sdp_cluster_val_availability_zone
aws_redshift_cluster_cluster_identifier                    = var.aws_redshift_cluster_sdp_cluster_val_cluster_identifier
aws_redshift_cluster_cluster_parameter_group_name          = var.aws_redshift_cluster_sdp_cluster_val_cluster_parameter_group_name
aws_redshift_cluster_cluster_public_key                    = var.aws_redshift_cluster_sdp_cluster_val_cluster_public_key
aws_redshift_cluster_cluster_revision_number               = var.aws_redshift_cluster_sdp_cluster_val_cluster_revision_number
aws_redshift_cluster_cluster_subnet_group_name             = var.aws_redshift_cluster_sdp_cluster_val_cluster_subnet_group_name
aws_redshift_cluster_cluster_type                          = var.aws_redshift_cluster_sdp_cluster_val_cluster_type
aws_redshift_cluster_cluster_version                       = var.aws_redshift_cluster_sdp_cluster_val_cluster_version
aws_redshift_cluster_database_name                         = var.aws_redshift_cluster_sdp_cluster_val_database_name
aws_redshift_cluster_encrypted                             = var.aws_redshift_cluster_sdp_cluster_val_encrypted
aws_redshift_cluster_endpoint                              = var.aws_redshift_cluster_sdp_cluster_val_endpoint
aws_redshift_cluster_enhanced_vpc_routing                  = var.aws_redshift_cluster_sdp_cluster_val_enhanced_vpc_routing
aws_redshift_cluster_iam_roles                             = var.aws_redshift_cluster_sdp_cluster_val_iam_roles
aws_redshift_cluster_kms_key_id                            = var.aws_redshift_cluster_sdp_cluster_val_kms_key_id
aws_redshift_cluster_logging_enable                        = var.aws_redshift_cluster_sdp_cluster_val_logging_enable
aws_redshift_cluster_master_username                       = var.aws_redshift_cluster_sdp_cluster_val_master_username
aws_redshift_cluster_node_type                             = var.aws_redshift_cluster_sdp_cluster_val_node_type
aws_redshift_cluster_number_of_nodes                       = var.aws_redshift_cluster_sdp_cluster_val_number_of_nodes
aws_redshift_cluster_port                                  = var.aws_redshift_cluster_sdp_cluster_val_port
aws_redshift_cluster_preferred_maintenance_window          = var.aws_redshift_cluster_sdp_cluster_val_preferred_maintenance_window
aws_redshift_cluster_skip_final_snapshot                   = var.aws_redshift_cluster_sdp_cluster_val_skip_final_snapshot
aws_redshift_cluster_tc_category                           = var.aws_redshift_cluster_sdp_cluster_val_tc_category
aws_redshift_cluster_vpc_security_group_ids                = var.aws_redshift_cluster_sdp_cluster_val_vpc_security_group_ids

}
